// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvnmMVWfwxZ5Q3CDwcQbc3YbyovyZm7hk',
    appId: '1:1093231399547:web:86f051a4550d25963748de',
    messagingSenderId: '1093231399547',
    projectId: 'knotique-68408',
    authDomain: 'knotique-68408.firebaseapp.com',
    storageBucket: 'knotique-68408.firebasestorage.app',
    measurementId: 'G-V03H30YMH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoshG58t7AExeAVgCuFeGk_dkHAae2Bh0',
    appId: '1:1093231399547:android:9a7ed7f947d52c6c3748de',
    messagingSenderId: '1093231399547',
    projectId: 'knotique-68408',
    storageBucket: 'knotique-68408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWTVurvBwwT6XjClGLmU523AgV3_amTpo',
    appId: '1:1093231399547:ios:f5d9724fe20d33a33748de',
    messagingSenderId: '1093231399547',
    projectId: 'knotique-68408',
    storageBucket: 'knotique-68408.firebasestorage.app',
    iosBundleId: 'com.example.crochet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWTVurvBwwT6XjClGLmU523AgV3_amTpo',
    appId: '1:1093231399547:ios:f5d9724fe20d33a33748de',
    messagingSenderId: '1093231399547',
    projectId: 'knotique-68408',
    storageBucket: 'knotique-68408.firebasestorage.app',
    iosBundleId: 'com.example.crochet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvnmMVWfwxZ5Q3CDwcQbc3YbyovyZm7hk',
    appId: '1:1093231399547:web:d6f54632f14a69153748de',
    messagingSenderId: '1093231399547',
    projectId: 'knotique-68408',
    authDomain: 'knotique-68408.firebaseapp.com',
    storageBucket: 'knotique-68408.firebasestorage.app',
    measurementId: 'G-ZTWYPT8SD6',
  );
}
