name: corona_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  animated_text_kit: ^4.2.3
  pie_chart: ^5.4.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.jpg"  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
