name: weather_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.2
  lottie: ^3.3.1
  intl: ^0.20.2
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.0+3
  flutter_launcher_icons: ^0.13.1   # Added launcher icons package

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpg"
